### ISSUE TITLE
Setup.py 

### ISSUE THREAD

**Issue by necrose99** [MatthewZito/Brutus#2]
setuppy-generator · PyPI

https://github.com/pyscaffold/pyscaffold can be a tad overkill , (git repo, setup.py , documentation,  tox , testing etc)

Yara-python ebuild.. @pentoo easy to fork for template
Lot messier to /opt/brutus , ln s , usr bin..  etc.. 
Gentoo linux , the python eclass dose all the heavy lifting.. 
How ever setup.py for the automated build etc. 

Likewise,  easier on deb.. pkging also.

**Comment by MatthewZito** [comment]
Much appreciated.
